development:
  username: 'AdditiveAnalytics'
  password: 'AdditiveAnalytics123!!'
  unity_service_url: "http://aws-pehr-13.unitysandbox.com/Unity/UnityService.svc/json"
  appname: 'AdditiveAnalytics.TestApp'

test:
  username: 'AdditiveAnalytics'
  password: 'AdditiveAnalytics123!!'
  unity_service_url: "http://aws-pehr-13.unitysandbox.com/Unity/UnityService.svc/json"
  appname: 'AdditiveAnalytics.TestApp'

production:
  username: 'AdditiveAnalytics'
  password: 'AdditiveAnalytics123!!'
  unity_service_url: "http://aws-pehr-13.unitysandbox.com/Unity/UnityService.svc/json"
  appname: 'AdditiveAnalytics.TestApp'

