hepatitis_b:
  patient_age_in_months:
    - 0 #Baby age, in months, when each dose is needed
    - 1
    - 6
rotavirus:
  rotarix:
    patient_age_in_months:
      - 2
      - 4
  rotateq:
    patient_age_in_months:
      - 2
      - 4
      - 6
diptheria_tetanus_pertussis:
  patient_age_in_months:
    - 2
    - 4
    - 6
    - 15
haemophilus_influenza:
  patient_age_in_months:
    - 2
    - 4
    - 6
    - 12
pneumococcal_conjugate:
  patient_age_in_months:
    - 2
    - 4
    - 6
    - 12
pneumococcal_polysaccharide:
poliovirus:
  patient_age_in_months:
    - 2
    - 4
    - 6
influenza:
  frequency: 'annual'
  cpt: ['90654','90655','90656','90657','90658','90661','90662','90672','90673','90685','90686','90688','Q2033','Q2035','Q2036','Q2037','Q2037','Q2038']
measles_mumps_rubella:
  doses_age_in_months:
    - 12
    - 48 # 4 years
varicella:
  patient_age_in_months:
    - 12
    - 48 # 4 years
hepatitis_a:
  patient_age_in_months:
    - 12
    - 18
human_papillomavirus:
  patient_age_in_years:
    - 132 # 11 years old
meningococcal:
  patient_age_in_months:
    - 132 # 11 years old
    - 192 # 16 years old
