hepatitis_a:
  doses: 2
  patient_age_in_months:
    - 12
    - 18
hepatitis_b:
  doses: 2
  patient_age_in_months:
    - 0 #Baby age, in months, when each dose is needed
    - 1
    - 6
rotavirus:
  rotarix:
    patient_age_in_months:
      - 2
      - 4
  rotateq:
    patient_age_in_months:
      - 2
      - 4
      - 6
diptheria_tetanus_pertussis:
  patient_age_in_months:
    - 2
    - 4
    - 6
    - 15
  booster_after:
    - 120 # 10 years
haemophilus_influenza:
  patient_age_in_months:
    - 2
    - 4
    - 6
    - 12
pneumococcal_conjugate:
  patient_age_in_months:
    - 2
    - 4
    - 6
    - 12
pneumococcal_polysaccharide:
poliovirus:
  patient_age_in_months:
    - 2
    - 4
    - 6
influenza:
  frequency: 'annual'
measles_mumps_rubella:
  doses_age_in_months:
    - 12
    - 48 # 4 years
varicella:
  doses: 2
  patient_age_in_months:
    - 12
    - 48 # 4 years
human_papillomavirus:
  doses: 3
  patient_age_in_years:
    - 132 # 11 years old
meningococcal:
  patient_age_in_months:
    - 132 # 11 years old
    - 192 # 16 years old
zoster: #shingles
  cpt: 90736
  patient_age_in_months:
    - 720 # 60 years old
