hepatitis_a:
  cpt: "'90632', '90633','90634','90636','90730'"
  doses: 2
  patient_age_in_months:
    - 12
    - 18
hepatitis_b:
  cpt: "'90746','90743','90745','90636','90740','90747'"
  doses: 3
  patient_age_in_months:
    - 0 #Baby age, in months, when each dose is needed
    - 1
    - 6
rotavirus:
  rotarix:
    patient_age_in_months:
      - 2
      - 4
  rotateq:
    patient_age_in_months:
      - 2
      - 4
      - 6
diptheria_tetanus_pertussis:
  patient_age_in_months:
    - 2
    - 4
    - 6
    - 15
  booster_after:
    - 120 # 10 years
haemophilus_influenza:
  patient_age_in_months:
    - 2
    - 4
    - 6
    - 12
pneumococcal_conjugate:
  patient_age_in_months:
    - 2
    - 4
    - 6
    - 12
pneumococcal_polysaccharide:
poliovirus:
  patient_age_in_months:
    - 2
    - 4
    - 6
influenza:
  cpt: "'90654', '90655', '90656', '90657', '90658', '90661', '90662', '90672', '90673', '90685', '90686', '90688', 'Q2033', 'Q2035', 'Q2036', 'Q2037', 'Q2037', 'Q2038'"
  frequency: 'annual'
measles_mumps_rubella:
  cpt: "'90707'"
  patient_age_in_months:
    - 12
    - 48 # 4 years
varicella:
  cpt: "'90710', '90716'"
  doses: 2
  patient_age_in_months:
    - 12
    - 48 # 4 years
human_papillomavirus:
  cpt: "'90649', '90650'"
  doses: 3
  patient_age_in_months:
    - 132 # 11 years old
meningococcal:
  cpt: "'90644', '90733', '90734'"
  patient_age_in_months:
    - 132 # 11 years old
    - 192 # 16 years old
zoster: #shingles
  cpt: '90736'
  patient_age_in_months:
    - 720 # 60 years old
