hepatitis_a:
  cpt: "'90632', '90633','90634','90636','90730'"
  doses: 2
  patient_age_in_months:
    - 12
    - 18
hepatitis_b:
  cpt: "'90746','90743','90745','90636','90740','90747'"
  doses: 3
  patient_age_in_months:
    - 0 #Baby age, in months, when each dose is needed
    - 1
    - 6
rotavirus:
  cpt: "'90680', '90681'"
  rotarix:
    cpt: "'90681'"
    patient_age_in_months:
      - 1.5
      - 3.5
  rotateq:
    cpt: "'90680'"
    patient_age_in_months:
      - 1.5
      - 4
      - 6
diptheria_tetanus_pertussis:
  cpt: "'90460', '90461', '90471', '90472', '90700', '90715'"
  patient_age_in_months:
    - 2
    - 4
    - 6
    - 15
    - 120 # Booster after 10 years
haemophilus_influenza:
  cpt: "'90645', '90646', '90647', '90648'"
  patient_age_in_months:
    - 2
    - 4
    - 6
    - 12
pneumococcal_conjugate:
  cpt: "'90669', '90670'"
  patient_age_in_months:
    - 2
    - 4
    - 6
    - 12
pneumococcal_polysaccharide:
  cpt: "'90669', '90670', '90732'"
  patient_age_in_months:
    - 780 # Age 65+
poliovirus:
  cpt: "'90698', '90712', '90713', '90723'"
  patient_age_in_months:
    - 2
    - 4
    - 6
    - 48 # Booster dose at 4-6 years
influenza:
  cpt: "'90654', '90655', '90656', '90657', '90658', '90661', '90662', '90672', '90673', '90685', '90686', '90688', 'Q2033', 'Q2035', 'Q2036', 'Q2037', 'Q2037', 'Q2038'"
  frequency: 'annual'
measles_mumps_rubella:
  cpt: "'90707'"
  patient_age_in_months:
    - 12
    - 48 # 4 years
varicella:
  cpt: "'90710', '90716'"
  doses: 2
  patient_age_in_months:
    - 12
    - 48 # 4 years
human_papillomavirus:
  cpt: "'90649', '90650'"
  doses: 3
  patient_age_in_months:
    - 132 # 11 years old
meningococcal:
  cpt: "'90644', '90733', '90734'"
  patient_age_in_months:
    - 132 # 11 years old
    - 192 # 16 years old
zoster: #shingles
  cpt: '90736'
  patient_age_in_months:
    - 720 # 60 years old
